



const language = {


    'en': {

        'pressToShow': 'Show',

        'Titles': {
            'General': 'General',
            'Connection': 'Connection',
            'DNS': 'DNS',
            'Pattern': 'Pattern',
            'Advanced': 'Advanced',
            'Survey': 'Survey',
        },

        'off': 'Off',
        'on': 'On',

        'useDefault': 'Use Default',
        'useCustom': 'Use Custom',
        'saveChanges': 'Save Changes',
        'saved': 'Saved',

        'Connection': {
            'connectionInformation': 'Connectivity Information',
            'connection': 'Connection',
            'isp': 'ISP',
            'colocationCenter': 'Colocation Center',

            'yourDevice': 'Your Device',
            'connectionType': 'Connection Type',
            'publicIP': 'Public IP',
            'deviceInformation': 'Device Information',
        },

        'ConnectionPage': {
            'address': 'Address',
            'port': 'Port',
            'adressDescription': 'Sets the local address the proxy server listens on.',
            'portDescription': 'Sets the local port the proxy server listens on.',   
        },

        'DNSPage': {
            'dns': 'DNS',
            'dnsDescription': 'Specifies the DNS server address to use for resolving domain names.',
            'useGoogle': 'Use Google',
            'useCloudflare': 'Use Cloudflare',
            'useQuad9': 'Use Quad9',
            'useNextDNS': 'Use NextDNS',
            'useYandex': 'Use Yandex',
            'useAdGuard': 'Use AdGuard',
            'useMullvad': 'Use Mullvad',
            'useOpenDNS': 'Use OpenDNS',
            'useCustom': 'Use Custom',

            'customAddress': 'Custom Address',
            'customPort': 'Custom Port',
            'customAddressDescription': 'Sets the custom address and port for the DNS server.',
        },

        'PatternPage': {
            'pattern': 'Pattern',
            'patternDescription': 'Applies DPI bypass only to packets that match the given domain patterns.',
        },

        'AdvancedPage': {
            'dnsipv4Only': 'DNS IPv4 Only',
            'dnsipv4OnlyDescription': 'Use IPv4 DNS servers only.',

            'dnsOverHttps': 'DNS Over HTTPS',
            'dnsOverHttpsDescription': 'Use DNS over HTTPS.',

            'systemProxy': 'System Proxy',
            'systemProxyDescription': 'Use system proxy settings.',

            'useProxy': 'Use Proxy',
            'useProxyDescription': 'Use a proxy server.',

            'timeout': 'Timeout',
            'timeoutDescription': 'Set the timeout for DNS queries. (Sec)',

            'clientHelloChunkSize': 'Client Hello Chunk Size',
            'clientHelloChunkSizeDescription': 'Set the size of the client hello chunk.',
        },

        'SurveyPage': {
            'survey': 'Survey',
            'surveySubtitle': 'We would love to hear your feedback!',
        }

    },


    'tr': {

        'pressToShow': 'Göster',

        'Titles': {
            'General': 'Genel',
            'Connection': 'Bağlantı',
            'DNS': 'DNS',
            'Pattern': 'Desen',
            'Advanced': 'Gelişmiş',
            'Survey': 'Anket',
        },

        'off': 'Kapalı',
        'on': 'Açık',

        'useDefault': 'Varsayılanı Kullan',
        'useCustom': 'Özel Kullan',
        'saveChanges': 'Değişiklikleri Kaydet',
        'saved': 'Kaydedildi',

        'Connection': {
            'connectionInformation': 'Bağlantı Bilgileri',
            'connection': 'Bağlantı',
            'isp': 'Servis Sağlayıcı',
            'colocationCenter': 'Kolokasyon Merkezi',

            'yourDevice': 'Cihazınız',
            'connectionType': 'Bağlantı Türü',
            'publicIP': 'Genel IP',
            'deviceInformation': 'Cihaz Bilgisi',
        },

        'ConnectionPage': {
            'address': 'Adres',
            'port': 'Port',
            'adressDescription': 'Proxy sunucusunun dinlediği yerel adresi ayarlar.',
            'portDescription': 'Proxy sunucusunun dinlediği yerel portu ayarlar.',
        },

        'DNSPage': {
            'dns': 'DNS',
            'dnsDescription': 'Alan adlarını çözmek için kullanılacak DNS sunucu adresini belirtir.',
            'useGoogle': 'Google Kullan',
            'useCloudflare': 'Cloudflare Kullan',
            'useQuad9': 'Quad9 Kullan',
            'useNextDNS': 'NextDNS Kullan',
            'useYandex': 'Yandex Kullan',
            'useAdGuard': 'AdGuard Kullan',
            'useMullvad': 'Mullvad Kullan',
            'useOpenDNS': 'OpenDNS Kullan',
            'useCustom': 'Özel Kullan',

            'customAddress': 'Özel Adres',
            'customPort': 'Özel Port',
            'customAddressDescription': 'DNS sunucusu için özel adres ve port ayarlar.',
        },

        'PatternPage': {
            'pattern': 'Desen',
            'patternDescription': 'DPI atlamayı yalnızca verilen alan adı desenleriyle eşleşen paketlere uygular.',
        },

        'AdvancedPage': {
            'dnsipv4Only': 'Sadece DNS IPv4',
            'dnsipv4OnlyDescription': 'Sadece IPv4 DNS sunucularını kullanın.',
            'dnsOverHttps': 'DNS Üzerinden HTTPS',
            'dnsOverHttpsDescription': 'DNS\'i HTTPS üzerinden kullanın.',
            'systemProxy': 'Sistem Proxy',
            'systemProxyDescription': 'Sistem proxy ayarlarını kullanın.',
            'useProxy': 'Proxy Kullan',
            'useProxyDescription': 'Bir proxy sunucusu kullanın.',
            'timeout': 'Zaman Aşımı',
            'timeoutDescription': 'DNS sorguları için zaman aşımını ayarlar. (Saniye)',
            'clientHelloChunkSize': 'İstemci Merhaba Parçacık Boyutu',
            'clientHelloChunkSizeDescription': 'İstemci merhaba parçacık boyutunu ayarlar.',
        },

        'SurveyPage': {
            'survey': 'Anket',
            'surveySubtitle': 'Geri bildiriminizi duymak isteriz!',
        }

    },


    'de': {
        'pressToShow': 'Zeigen',
        'Titles': {
            'General': 'Allgemein',
            'Connection': 'Verbindung',
            'DNS': 'DNS',
            'Pattern': 'Muster',
            'Advanced': 'Erweitert',
            'Survey': 'Umfrage',
        },
        'off': 'Aus',
        'on': 'Ein',
        'useDefault': 'Standard verwenden',
        'useCustom': 'Benutzerdefiniert verwenden',
        'saveChanges': 'Änderungen speichern',
        'saved': 'Gespeichert',
        'Connection': {
            'connectionInformation': 'Verbindungsinformationen',
            'connection': 'Verbindung',
            'isp': 'ISP',
            'colocationCenter': 'Colocation Center',
            'yourDevice': 'Ihr Gerät',
            'connectionType': 'Verbindungstyp',
            'publicIP': 'Öffentliche IP',
            'deviceInformation': 'Geräteinformationen',
        },
        'ConnectionPage': {
            'address': 'Adresse',
            'port': 'Port',
            'adressDescription': 'Legt die lokale Adresse fest, auf der der Proxy-Server lauscht.',
            'portDescription': 'Legt den lokalen Port fest, auf dem der Proxy-Server lauscht.',
        },
        'DNSPage': {
            'dns': 'DNS',
            'dnsDescription': 'Legt die DNS-Serveradresse fest, die zum Auflösen von Domainnamen verwendet werden soll.',
            'useGoogle': 'Google verwenden',
            'useCloudflare': 'Cloudflare verwenden',
            'useQuad9': 'Quad9 verwenden',
            'useNextDNS': 'NextDNS verwenden',
            'useYandex': 'Yandex verwenden',
            'useAdGuard': 'AdGuard verwenden',
            'useMullvad': 'Mullvad verwenden',
            'useOpenDNS': 'OpenDNS verwenden',
            'useCustom': 'Benutzerdefiniert verwenden',

            'customAddress': 'Benutzerdefinierte Adresse',
            'customPort': 'Benutzerdefinierter Port',
            'customAddressDescription': 'Legt die benutzerdefinierte Adresse und den Port für den DNS-Server fest.',
        },
        'PatternPage': {
            'pattern': 'Muster',
            'patternDescription': 'Wendet die DPI-Umgehung nur auf Pakete an, die mit den angegebenen Domainmustern übereinstimmen.',
        },
        'AdvancedPage': {
            'dnsipv4Only': 'Nur DNS IPv4',
            'dnsipv4OnlyDescription': 'Verwenden Sie nur IPv4 DNS-Server.',
            'dnsOverHttps': 'DNS über HTTPS',
            'dnsOverHttpsDescription': 'Verwenden Sie DNS über HTTPS.',
            'systemProxy': 'Systemproxy',
            'systemProxyDescription': 'Verwenden Sie die Proxy-Einstellungen des Systems.',
            'useProxy': 'Proxy verwenden',
            'useProxyDescription': 'Verwenden Sie einen Proxy-Server.',
            'timeout': 'Zeitüberschreitung',
            'timeoutDescription': 'Legen Sie die Zeitüberschreitung für DNS-Abfragen fest. (Sek)',
            'clientHelloChunkSize': 'Client Hello Chunk-Größe',
            'clientHelloChunkSizeDescription': 'Legen Sie die Größe des Client-Hello-Chunks fest.',
        },
        'SurveyPage': {
            'survey': 'Umfrage',
            'surveySubtitle': 'Wir würden uns freuen, Ihr Feedback zu hören!',
        }
    },

    'es': {
        'pressToShow': 'Mostrar',
        'Titles': {
            'General': 'General',
            'Connection': 'Conexión',
            'DNS': 'DNS',
            'Pattern': 'Patrón',
            'Advanced': 'Avanzado',
            'Survey': 'Encuesta',
        },
        'off': 'Apagar',
        'on': 'Encender',
        'useDefault': 'Usar Predeterminado',
        'useCustom': 'Usar Personalizado',
        'saveChanges': 'Guardar Cambios',
        'saved': 'Guardado',
        'Connection': {
            'connectionInformation': 'Información de Conexión',
            'connection': 'Conexión',
            'isp': 'ISP',
            'colocationCenter': 'Centro de Colocación',
            'yourDevice': 'Tu Dispositivo',
            'connectionType': 'Tipo de Conexión',
            'publicIP': 'IP Pública',
            'deviceInformation': 'Información del Dispositivo',
        },
        'ConnectionPage': {
            'address': 'Dirección',
            'port': 'Puerto',
            'adressDescription': 'Establece la dirección local en la que escucha el servidor proxy.',
            'portDescription': 'Establece el puerto local en el que escucha el servidor proxy.',
        },
        'DNSPage': {
            'dns': 'DNS',
            'dnsDescription': 'Especifica la dirección del servidor DNS que se utilizará para resolver nombres de dominio.',
            'useGoogle': 'Usar Google',
            'useCloudflare': 'Usar Cloudflare',
            'useQuad9': 'Usar Quad9',
            'useNextDNS': 'Usar NextDNS',
            'useYandex': 'Usar Yandex',
            'useAdGuard': 'Usar AdGuard',
            'useMullvad': 'Usar Mullvad',
            'useOpenDNS': 'Usar OpenDNS',
            'useCustom': 'Usar Personalizado',
            'customAddress': 'Dirección Personalizada',
            'customPort': 'Puerto Personalizado',
            'customAddressDescription': 'Establece la dirección y el puerto personalizados para el servidor DNS.',
        },
        'PatternPage': {
            'pattern': 'Patrón',
            'patternDescription': 'Aplica la omisión de DPI solo a los paquetes que coinciden con los patrones de dominio dados.',
        },
        'AdvancedPage': {
            'dnsipv4Only': 'Solo DNS IPv4',
            'dnsipv4OnlyDescription': 'Usar solo servidores DNS IPv4.',
            'dnsOverHttps': 'DNS sobre HTTPS',
            'dnsOverHttpsDescription': 'Usar DNS sobre HTTPS.',
            'systemProxy': 'Proxy del Sistema',
            'systemProxyDescription': 'Usar la configuración de proxy del sistema.',
            'useProxy': 'Usar Proxy',
            'useProxyDescription': 'Usar un servidor proxy.',
            'timeout': 'Tiempo de Espera',
            'timeoutDescription': 'Establecer el tiempo de espera para las consultas DNS. (Seg)',
            'clientHelloChunkSize': 'Tamaño de Fragmento de Client Hello',
            'clientHelloChunkSizeDescription': 'Establecer el tamaño del fragmento de client hello.',
        },
        'SurveyPage': {
            'survey': 'Encuesta',
            'surveySubtitle': '¡Nos encantaría escuchar tus comentarios!',
        }
    },

    'fr': {
        'pressToShow': 'Afficher',
        'Titles': {
            'General': 'Général',
            'Connection': 'Connexion',
            'DNS': 'DNS',
            'Pattern': 'Modèle',
            'Advanced': 'Avancé',
            'Survey': 'Enquête',
        },
        'off': 'Éteindre',
        'on': 'Allumer',
        'useDefault': 'Utiliser par défaut',
        'useCustom': 'Utiliser personnalisé',
        'saveChanges': 'Enregistrer les modifications',
        'saved': 'Enregistré',
        'Connection': {
            'connectionInformation': 'Informations de connexion',
            'connection': 'Connexion',
            'isp': 'Fournisseur d\'accès Internet',
            'colocationCenter': 'Centre de colocation',
            'yourDevice': 'Votre appareil',
            'connectionType': 'Type de connexion',
            'publicIP': 'IP publique',
            'deviceInformation': 'Informations sur l\'appareil',
        },
        'ConnectionPage': {
            'address': 'Adresse',
            'port': 'Port',
            'adressDescription': 'Définit l\'adresse locale sur laquelle le serveur proxy écoute.',
            'portDescription': 'Définit le port local sur lequel le serveur proxy écoute.',
        },
        'DNSPage': {
            'dns': 'DNS',
            'dnsDescription': 'Spécifie l\'adresse du serveur DNS à utiliser pour résoudre les noms de domaine.',
            'useGoogle': 'Utiliser Google',
            'useCloudflare': 'Utiliser Cloudflare',
            'useQuad9': 'Utiliser Quad9',
            'useNextDNS': 'Utiliser NextDNS',
            'useYandex': 'Utiliser Yandex',
            'useAdGuard': 'Utiliser AdGuard',
            'useMullvad': 'Utiliser Mullvad',
            'useOpenDNS': 'Utiliser OpenDNS',
            'useCustom': 'Utiliser personnalisé',
            'customAddress': 'Adresse personnalisée',
            'customPort': 'Port personnalisé',
            'customAddressDescription': 'Définit l\'adresse et le port personnalisés pour le serveur DNS.',
        },
        'PatternPage': {
            'pattern': 'Modèle',
            'patternDescription': 'Applique le contournement DPI uniquement aux paquets qui correspondent aux modèles de domaine donnés.',
        },
        'AdvancedPage': {
            'dnsipv4Only': 'DNS IPv4 uniquement',
            'dnsipv4OnlyDescription': 'Utiliser uniquement les serveurs DNS IPv4.',
            'dnsOverHttps': 'DNS sur HTTPS',
            'dnsOverHttpsDescription': 'Utiliser DNS sur HTTPS.',
            'systemProxy': 'Proxy système',
            'systemProxyDescription': 'Utiliser les paramètres de proxy système.',
            'useProxy': 'Utiliser un proxy',
            'useProxyDescription': 'Utiliser un serveur proxy.',
            'timeout': 'Délai d\'attente',
            'timeoutDescription': 'Définir le délai d\'attente pour les requêtes DNS. (Sec)',
            'clientHelloChunkSize': 'Taille du morceau Client Hello',
            'clientHelloChunkSizeDescription': 'Définir la taille du morceau client hello.',
        },
        'SurveyPage': {
            'survey': 'Enquête',
            'surveySubtitle': 'Nous aimerions avoir vos commentaires !',
        }
    },
    'it': {
        'pressToShow': 'Mostra',
        'Titles': {
            'General': 'Generale',
            'Connection': 'Connessione',
            'DNS': 'DNS',
            'Pattern': 'Modello',
            'Advanced': 'Avanzato',
            'Survey': 'Sondaggio',
        },
        'off': 'Spento',
        'on': 'Acceso',
        'useDefault': 'Usa Predefinito',
        'useCustom': 'Usa Personalizzato',
        'saveChanges': 'Salva Modifiche',
        'saved': 'Salvato',
        'Connection': {
            'connectionInformation': 'Informazioni di Connessione',
            'connection': 'Connessione',
            'isp': 'ISP',
            'colocationCenter': 'Centro di Colocazione',
            'yourDevice': 'Il Tuo Dispositivo',
            'connectionType': 'Tipo di Connessione',
            'publicIP': 'IP Pubblico',
            'deviceInformation': 'Informazioni sul Dispositivo',
        },
        'ConnectionPage': {
            'address': 'Indirizzo',
            'port': 'Porta',
            'adressDescription': 'Imposta l\'indirizzo locale su cui il server proxy ascolta.',
            'portDescription': 'Imposta la porta locale su cui il server proxy ascolta.',
        },
        'DNSPage': {
            'dns': 'DNS',
            'dnsDescription': 'Specifica l\'indirizzo del server DNS da utilizzare per risolvere i nomi di dominio.',
            'useGoogle': 'Usa Google',
            'useCloudflare': 'Usa Cloudflare',
            'useQuad9': 'Usa Quad9',
            'useNextDNS': 'Usa NextDNS',
            'useYandex': 'Usa Yandex',
            'useAdGuard': 'Usa AdGuard',
            'useMullvad': 'Usa Mullvad',
            'useOpenDNS': 'Usa OpenDNS',
            'useCustom': 'Usa Personalizzato',
            'customAddress': 'Indirizzo Personalizzato',
            'customPort': 'Porta Personalizzata',
            'customAddressDescription': 'Imposta l\'indirizzo e la porta personalizzati per il server DNS.',
        },
        'PatternPage': {
            'pattern': 'Modello',
            'patternDescription': 'Applica il bypass DPI solo ai pacchetti che corrispondono ai modelli di dominio forniti.',
        },
        'AdvancedPage': {
            'dnsipv4Only': 'Solo DNS IPv4',
            'dnsipv4OnlyDescription': 'Usa solo server DNS IPv4.',
            'dnsOverHttps': 'DNS su HTTPS',
            'dnsOverHttpsDescription': 'Usa DNS su HTTPS.',
            'systemProxy': 'Proxy di Sistema',
            'systemProxyDescription': 'Usa le impostazioni proxy di sistema.',
            'useProxy': 'Usa Proxy',
            'useProxyDescription': 'Usa un server proxy.',
            'timeout': 'Timeout',
            'timeoutDescription': 'Imposta il timeout per le query DNS. (Sec)',
            'clientHelloChunkSize': 'Dimensione del Chunk Client Hello',
            'clientHelloChunkSizeDescription': 'Imposta la dimensione del chunk client hello.',
        },
        'SurveyPage': {
            'survey': 'Sondaggio',
            'surveySubtitle': 'Ci piacerebbe ricevere il tuo feedback!',
        }
    },
    'pt': {
        'pressToShow': 'Mostrar',
        'Titles': {
            'General': 'Geral',
            'Connection': 'Conexão',
            'DNS': 'DNS',
            'Pattern': 'Padrão',
            'Advanced': 'Avançado',
            'Survey': 'Pesquisa',
        },
        'off': 'Desligado',
        'on': 'Ligado',
        'useDefault': 'Usar Padrão',
        'useCustom': 'Usar Personalizado',
        'saveChanges': 'Salvar Alterações',
        'saved': 'Salvo',
        'Connection': {
            'connectionInformation': 'Informações de Conexão',
            'connection': 'Conexão',
            'isp': 'ISP',
            'colocationCenter': 'Centro de Colocação',
            'yourDevice': 'Seu Dispositivo',
            'connectionType': 'Tipo de Conexão',
            'publicIP': 'IP Público',
            'deviceInformation': 'Informações do Dispositivo',
        },
        'ConnectionPage': {
            'address': 'Endereço',
            'port': 'Porta',
            'adressDescription': 'Define o endereço local no qual o servidor proxy escuta.',
            'portDescription': 'Define a porta local na qual o servidor proxy escuta.',
        },
        'DNSPage': {
            'dns': 'DNS',
            'dnsDescription': 'Especifica o endereço do servidor DNS a ser usado para resolver nomes de domínio.',
            'useGoogle': 'Usar Google',
            'useCloudflare': 'Usar Cloudflare',
            'useQuad9': 'Usar Quad9',
            'useNextDNS': 'Usar NextDNS',
            'useYandex': 'Usar Yandex',
            'useAdGuard': 'Usar AdGuard',
            'useMullvad': 'Usar Mullvad',
            'useOpenDNS': 'Usar OpenDNS',
            'useCustom': 'Usar Personalizado',
            'customAddress': 'Endereço Personalizado',
            'customPort': 'Porta Personalizada',
            'customAddressDescription': 'Define o endereço e a porta personalizados para o servidor DNS.',
        },
        'PatternPage': {
            'pattern': 'Padrão',
            'patternDescription': 'Aplica a omissão de DPI apenas aos pacotes que correspondem aos padrões de domínio fornecidos.',
        },
        'AdvancedPage': {
            'dnsipv4Only': 'Apenas DNS IPv4',
            'dnsipv4OnlyDescription': 'Usar apenas servidores DNS IPv4.',
            'dnsOverHttps': 'DNS sobre HTTPS',
            'dnsOverHttpsDescription': 'Usar DNS sobre HTTPS.',
            'systemProxy': 'Proxy do Sistema',
            'systemProxyDescription': 'Usar as configurações de proxy do sistema.',
            'useProxy': 'Usar Proxy',
            'useProxyDescription': 'Usar um servidor proxy.',
            'timeout': 'Tempo Limite',
            'timeoutDescription': 'Definir o tempo limite para consultas DNS. (Seg)',
            'clientHelloChunkSize': 'Tamanho do Chunk Client Hello',
            'clientHelloChunkSizeDescription': 'Definir o tamanho do chunk client hello.',
        },
        'SurveyPage': {
            'survey': 'Pesquisa',
            'surveySubtitle': 'Adoraríamos ouvir seu feedback!',
        }
    },
    'ru': {
        'pressToShow': 'Показать',
        'Titles': {
            'General': 'Общие',
            'Connection': 'Соединение',
            'DNS': 'DNS',
            'Pattern': 'Шаблон',
            'Advanced': 'Расширенный',
            'Survey': 'Опрос',
        },
        'off': 'Выключить',
        'on': 'Включить',
        'useDefault': 'Использовать по умолчанию',
        'useCustom': 'Использовать пользовательский',
        'saveChanges': 'Сохранить изменения',
        'saved': 'Сохранено',
        'Connection': {
            'connectionInformation': 'Информация о подключении',
            'connection': 'Соединение',
            'isp': 'Провайдер',
            'colocationCenter': 'Центр размещения',
            'yourDevice': 'Ваше устройство',
            'connectionType': 'Тип соединения',
            'publicIP': 'Публичный IP',
            'deviceInformation': 'Информация об устройстве',
        },
        'ConnectionPage': {
            'address': 'Адрес',
            'port': 'Порт',
            'adressDescription': 'Устанавливает локальный адрес, на котором прослушивает прокси-сервер.',
            'portDescription': 'Устанавливает локальный порт, на котором прослушивает прокси-сервер.',
        },
        'DNSPage': {
            'dns': 'DNS',
            'dnsDescription': 'Указывает адрес DNS-сервера, который будет использоваться для разрешения доменных имен.',
            'useGoogle': 'Использовать Google',
            'useCloudflare': 'Использовать Cloudflare',
            'useQuad9': 'Использовать Quad9',
            'useNextDNS': 'Использовать NextDNS',
            'useYandex': 'Использовать Yandex',
            'useAdGuard': 'Использовать AdGuard',
            'useMullvad': 'Использовать Mullvad',
            'useOpenDNS': 'Использовать OpenDNS',
            'useCustom': 'Использовать пользовательский',
            'customAddress': 'Пользовательский адрес',
            'customPort': 'Пользовательский порт',
            'customAddressDescription': 'Устанавливает пользовательский адрес и порт для DNS-сервера.',
        },
        'PatternPage': {
            'pattern': 'Шаблон',
            'patternDescription': 'Применяет обход DPI только к пакетам, которые соответствуют заданным шаблонам домена.',
        },
        'AdvancedPage': {
            'dnsipv4Only': 'Только DNS IPv4',
            'dnsipv4OnlyDescription': 'Использовать только IPv4 DNS-серверы.',
            'dnsOverHttps': 'DNS через HTTPS',
            'dnsOverHttpsDescription': 'Использовать DNS через HTTPS.',
            'systemProxy': 'Системный прокси',
            'systemProxyDescription': 'Использовать настройки прокси-сервера системы.',
            'useProxy': 'Использовать прокси',
            'useProxyDescription': 'Использовать прокси-сервер.',
            'timeout': 'Тайм-аут',
            'timeoutDescription': 'Установить тайм-аут для DNS-запросов. (Сек)',
            'clientHelloChunkSize': 'Размер чанка Client Hello',
            'clientHelloChunkSizeDescription': 'Установить размер чанка client hello.',
        },
        'SurveyPage': {
            'survey': 'Опрос',
            'surveySubtitle': 'Мы хотели бы услышать ваши отзывы!',
        }
    },
    'ja': {
        'pressToShow': '表示',
        'Titles': {
            'General': '一般',
            'Connection': '接続',
            'DNS': 'DNS',
            'Pattern': 'パターン',
            'Advanced': '高度な',
            'Survey': '調査',
        },
        'off': 'オフ',
        'on': 'オン',
        'useDefault': 'デフォルトを使用',
        'useCustom': 'カスタムを使用',
        'saveChanges': '変更を保存',
        'saved': '保存済み',
        'Connection': {
            'connectionInformation': '接続情報',
            'connection': '接続',
            'isp': 'ISP',
            'colocationCenter': 'コロケーションセンター',
            'yourDevice': 'あなたのデバイス',
            'connectionType': '接続タイプ',
            'publicIP': 'パブリックIP',
            'deviceInformation': 'デバイス情報',
        },
        'ConnectionPage': {
            'address': 'アドレス',
            'port': 'ポート',
            'adressDescription': 'プロキシサーバーがリッスンするローカルアドレスを設定します。',
            'portDescription': 'プロキシサーバーがリッスンするローカルポートを設定します。',
        },
        'DNSPage': {
            'dns': 'DNS',
            'dnsDescription': 'ドメイン名を解決するために使用するDNSサーバーのアドレスを指定します。',
            'useGoogle': 'Googleを使用',
            'useCloudflare': 'Cloudflareを使用',
            'useQuad9': 'Quad9を使用',
            'useNextDNS': 'NextDNSを使用',
            'useYandex': 'Yandexを使用',
            'useAdGuard': 'AdGuardを使用',
            'useMullvad': 'Mullvadを使用',
            'useOpenDNS': 'OpenDNSを使用',
            'useCustom': 'カスタムを使用',
            'customAddress': 'カスタムアドレス',
            'customPort': 'カスタムポート',
            'customAddressDescription': 'DNSサーバーのカスタムアドレスとポートを設定します。',
        },
        'PatternPage': {
            'pattern': 'パターン',
            'patternDescription': '指定されたドメインパターンと一致するパケットにのみDPIバイパスを適用します。',
        },
        'AdvancedPage': {
            'dnsipv4Only': 'DNS IPv4のみ',
            'dnsipv4OnlyDescription': 'IPv4 DNSサーバーのみを使用します。',
            'dnsOverHttps': 'HTTPS経由のDNS',
            'dnsOverHttpsDescription': 'HTTPS経由でDNSを使用します。',
            'systemProxy': 'システムプロキシ',
            'systemProxyDescription': 'システムのプロキシ設定を使用します。',
            'useProxy': 'プロキシを使用',
            'useProxyDescription': 'プロキシサーバーを使用します。',
            'timeout': 'タイムアウト',
            'timeoutDescription': 'DNSクエリのタイムアウトを設定します。 (秒)',
            'clientHelloChunkSize': 'クライアントHelloチャンクサイズ',
            'clientHelloChunkSizeDescription': 'クライアントHelloチャンクのサイズを設定します。',
        },
        'SurveyPage': {
            'survey': '調査',
            'surveySubtitle': 'あなたのフィードバックを聞きたいです！',
        }
    },
    'ko': {
        'pressToShow': '표시',
        'Titles': {
            'General': '일반',
            'Connection': '연결',
            'DNS': 'DNS',
            'Pattern': '패턴',
            'Advanced': '고급',
            'Survey': '설문조사',
        },
        'off': '꺼짐',
        'on': '켜짐',
        'useDefault': '기본값 사용',
        'useCustom': '사용자 정의 사용',
        'saveChanges': '변경 사항 저장',
        'saved': '저장됨',
        'Connection': {
            'connectionInformation': '연결 정보',
            'connection': '연결',
            'isp': 'ISP',
            'colocationCenter': '콜로케이션 센터',
            'yourDevice': '당신의 장치',
            'connectionType': '연결 유형',
            'publicIP': '공용 IP',
            'deviceInformation': '장치 정보',
        },
        'ConnectionPage': {
            'address': '주소',
            'port': '포트',
            'adressDescription': '프록시 서버가 수신 대기하는 로컬 주소를 설정합니다.',
            'portDescription': '프록시 서버가 수신 대기하는 로컬 포트를 설정합니다.',
        },
        'DNSPage': {
            'dns': 'DNS',
            'dnsDescription': '도메인 이름을 확인하는 데 사용할 DNS 서버 주소를 지정합니다.',
            'useGoogle': 'Google 사용',
            'useCloudflare': 'Cloudflare 사용',
            'useQuad9': 'Quad9 사용',
            'useNextDNS': 'NextDNS 사용',
            'useYandex': 'Yandex 사용',
            'useAdGuard': 'AdGuard 사용',
            'useMullvad': 'Mullvad 사용',
            'useOpenDNS': 'OpenDNS 사용',
            'useCustom': '사용자 정의 사용',
            'customAddress': '사용자 정의 주소',
            'customPort': '사용자 정의 포트',
            'customAddressDescription': 'DNS 서버의 사용자 정의 주소 및 포트를 설정합니다.',
        },
        'PatternPage': {
            'pattern': '패턴',
            'patternDescription': '지정된 도메인 패턴과 일치하는 패킷에만 DPI 우회를 적용합니다.',
        },
        'AdvancedPage': {
            'dnsipv4Only': 'DNS IPv4 전용',
            'dnsipv4OnlyDescription': 'IPv4 DNS 서버만 사용합니다.',
            'dnsOverHttps': 'HTTPS를 통한 DNS',
            'dnsOverHttpsDescription': 'HTTPS를 통한 DNS를 사용합니다.',
            'systemProxy': '시스템 프록시',
            'systemProxyDescription': '시스템 프록시 설정을 사용합니다.',
            'useProxy': '프록시 사용',
            'useProxyDescription': '프록시 서버를 사용합니다.',
            'timeout': '시간 초과',
            'timeoutDescription': 'DNS 쿼리의 시간 초과를 설정합니다. (초)',
            'clientHelloChunkSize': '클라이언트 Hello 청크 크기',
            'clientHelloChunkSizeDescription': '클라이언트 Hello 청크의 크기를 설정합니다.',
        },
        'SurveyPage': {
            'survey': '설문조사',
            'surveySubtitle': '귀하의 피드백을 듣고 싶습니다!',
        }
    },
    'zh': {
        'pressToShow': '显示',
        'Titles': {
            'General': '一般',
            'Connection': '连接',
            'DNS': 'DNS',
            'Pattern': '模式',
            'Advanced': '高级',
            'Survey': '调查',
        },
        'off': '关闭',
        'on': '打开',
        'useDefault': '使用默认',
        'useCustom': '使用自定义',
        'saveChanges': '保存更改',
        'saved': '已保存',
        'Connection': {
            'connectionInformation': '连接信息',
            'connection': '连接',
            'isp': 'ISP',
            'colocationCenter': '机柜中心',
            'yourDevice': '您的设备',
            'connectionType': '连接类型',
            'publicIP': '公共IP',
            'deviceInformation': '设备信息',
        },
        'ConnectionPage': {
            'address': '地址',
            'port': '端口',
            'adressDescription': '设置代理服务器侦听的本地地址。',
            'portDescription': '设置代理服务器侦听的本地端口。',
        },
        'DNSPage': {
            'dns': 'DNS',
            'dnsDescription': '指定用于解析域名的 DNS 服务器地址。',
            'useGoogle': '使用谷歌',
            'useCloudflare': '使用 Cloudflare',
            'useQuad9': '使用 Quad9',
            'useNextDNS': '使用 NextDNS',
            'useYandex': '使用 Yandex',
            'useAdGuard': '使用 AdGuard',
            'useMullvad': '使用 Mullvad',
            'useOpenDNS': '使用 OpenDNS',
            'useCustom': '使用自定义',
            'customAddress': '自定义地址',
            'customPort': '自定义端口',
            'customAddressDescription': '设置 DNS 服务器的自定义地址和端口。',
        },
        'PatternPage': {
            'pattern': '模式',
            'patternDescription': '仅将 DPI 绕过应用于与给定域模式匹配的数据包。',
        },
        'AdvancedPage': {
            'dnsipv4Only': '仅 DNS IPv4',
            'dnsipv4OnlyDescription': '仅使用 IPv4 DNS 服务器。',
            'dnsOverHttps': 'HTTPS 上的 DNS',
            'dnsOverHttpsDescription': '使用 HTTPS 上的 DNS。',
            'systemProxy': '系统代理',
            'systemProxyDescription': '使用系统代理设置。',
            'useProxy': '使用代理',
            'useProxyDescription': '使用代理服务器。',
            'timeout': '超时',
            'timeoutDescription': '设置 DNS 查询的超时。 (秒)',
            'clientHelloChunkSize': '客户端 Hello 块大小',
            'clientHelloChunkSizeDescription': '设置客户端 hello 块的大小。',
        },
        'SurveyPage': {
            'survey': '调查',
            'surveySubtitle': '我们很想听听您的反馈！',
        }
    },
    'ar': {
        'pressToShow': 'عرض',
        'Titles': {
            'General': 'عام',
            'Connection': 'اتصال',
            'DNS': 'DNS',
            'Pattern': 'نمط',
            'Advanced': 'متقدم',
            'Survey': 'استطلاع',
        },
        'off': 'إيقاف',
        'on': 'تشغيل',
        'useDefault': 'استخدام الافتراضي',
        'useCustom': 'استخدام مخصص',
        'saveChanges': 'حفظ التغييرات',
        'saved': 'تم الحفظ',
        'Connection': {
            'connectionInformation': 'معلومات الاتصال',
            'connection': 'اتصال',
            'isp': 'مزود خدمة الإنترنت',
            'colocationCenter': 'مركز التوزيع',
            'yourDevice': 'جهازك',
            'connectionType': 'نوع الاتصال',
            'publicIP': 'IP العامة',
            'deviceInformation': 'معلومات الجهاز',
        },
        'ConnectionPage': {
            'address': 'عنوان',
            'port': 'منفذ',
            'adressDescription': 'يحدد العنوان المحلي الذي يستمع إليه خادم الوكيل.',
            'portDescription': 'يحدد المنفذ المحلي الذي يستمع إليه خادم الوكيل.',
        },
        'DNSPage': {
            'dns': 'DNS',
            'dnsDescription': 'يحدد عنوان خادم DNS الذي سيتم استخدامه لحل أسماء النطاقات.',
            'useGoogle': 'استخدام جوجل',
            'useCloudflare': 'استخدام Cloudflare',
            'useQuad9': 'استخدام Quad9',
            'useNextDNS': 'استخدام NextDNS',
            'useYandex': 'استخدام Yandex',
            'useAdGuard': 'استخدام AdGuard',
            'useMullvad': 'استخدام Mullvad',
            'useOpenDNS': 'استخدام OpenDNS',
            'useCustom': 'استخدام مخصص',
            'customAddress': 'عنوان مخصص',
            'customPort': 'منفذ مخصص',
            'customAddressDescription': 'يحدد عنوان المنفذ المخصص لخادم DNS.',
        },
        'PatternPage': {
            'pattern': 'نمط',
            'patternDescription': 'يطبق تجاوز DPI فقط على الحزم التي تتطابق مع أنماط المجال المعطاة.',
        },
        'AdvancedPage': {
            'dnsipv4Only': 'DNS IPv4 فقط',
            'dnsipv4OnlyDescription': 'استخدام خوادم DNS IPv4 فقط.',
            'dnsOverHttps': 'DNS عبر HTTPS',
            'dnsOverHttpsDescription': 'استخدام DNS عبر HTTPS.',
            'systemProxy': 'وكيل النظام',
            'systemProxyDescription': 'استخدام إعدادات الوكيل للنظام.',
            'useProxy': 'استخدام الوكيل',
            'useProxyDescription': 'استخدام خادم وكيل.',
            'timeout': 'مهلة',
            'timeoutDescription': 'تعيين مهلة استعلامات DNS. (ثانية)',
            'clientHelloChunkSize': 'حجم كتلة عميل مرحبا',
            'clientHelloChunkSizeDescription': 'تعيين حجم كتلة عميل مرحبا.',
        },
        'SurveyPage': {
            'survey': 'استطلاع',
            'surveySubtitle': 'نود أن نسمع ملاحظاتك!',
        }
    },
    'pl': {
        'pressToShow': 'Pokaż',
        'Titles': {
            'General': 'Ogólne',
            'Connection': 'Połączenie',
            'DNS': 'DNS',
            'Pattern': 'Wzór',
            'Advanced': 'Zaawansowane',
            'Survey': 'Ankieta',
        },
        'off': 'Wyłączone',
        'on': 'Włączone',
        'useDefault': 'Użyj domyślnie',
        'useCustom': 'Użyj niestandardowego',
        'saveChanges': 'Zapisz zmiany',
        'saved': 'Zapisano',
        'Connection': {
            'connectionInformation': 'Informacje o połączeniu',
            'connection': 'Połączenie',
            'isp': 'ISP',
            'colocationCenter': 'Centrum kolokacyjne',
            'yourDevice': 'Twoje urządzenie',
            'connectionType': 'Typ połączenia',
            'publicIP': 'Publiczny IP',
            'deviceInformation': 'Informacje o urządzeniu',
        },
        'ConnectionPage': {
            'address': 'Adres',
            'port': 'Port',
            'adressDescription': 'Ustawia lokalny adres, na którym nasłuchuje serwer proxy.',
            'portDescription': 'Ustawia lokalny port, na którym nasłuchuje serwer proxy.',
        },
        'DNSPage': {
            'dns': 'DNS',
            'dnsDescription': 'Określa adres serwera DNS, który ma być używany do rozwiązywania nazw domen.',
            'useGoogle': 'Użyj Google',
            'useCloudflare': 'Użyj Cloudflare',
            'useQuad9': 'Użyj Quad9',
            'useNextDNS': 'Użyj NextDNS',
            'useYandex': 'Użyj Yandex',
            'useAdGuard': 'Użyj AdGuard',
            'useMullvad': 'Użyj Mullvad',
            'useOpenDNS': 'Użyj OpenDNS',
            'useCustom': 'Użyj niestandardowego',
            'customAddress': 'Niestandardowy adres',
            'customPort': 'Niestandardowy port',
            'customAddressDescription': 'Ustawia niestandardowy adres i port dla serwera DNS.',
        },
        'PatternPage': {
            'pattern': 'Wzór',
            'patternDescription': 'Zastosuj obejście DPI tylko do pakietów, które pasują do podanych wzorców domen.',
        },
        'AdvancedPage': {
            'dnsipv4Only': 'Tylko DNS IPv4',
            'dnsipv4OnlyDescription': 'Użyj tylko serwerów DNS IPv4.',
            'dnsOverHttps': 'DNS przez HTTPS',
            'dnsOverHttpsDescription': 'Użyj DNS przez HTTPS.',
            'systemProxy': 'Proxy systemowe',
            'systemProxyDescription': 'Użyj ustawień proxy systemu.',
            'useProxy': 'Użyj proxy',
            'useProxyDescription': 'Użyj serwera proxy.',
            'timeout': 'Limit czasu',
            'timeoutDescription': 'Ustaw limit czasu dla zapytań DNS. (Sek)',
            'clientHelloChunkSize': 'Rozmiar kawałka Client Hello',
            'clientHelloChunkSizeDescription': 'Ustaw rozmiar kawałka client hello.',
        },
        'SurveyPage': {
            'survey': 'Ankieta',
            'surveySubtitle': 'Chcielibyśmy usłyszeć Twoją opinię!',
        }
    },
    'uk': {
        'pressToShow': 'Показати',
        'Titles': {
            'General': 'Загальний',
            'Connection': 'З\'єднання',
            'DNS': 'DNS',
            'Pattern': 'Шаблон',
            'Advanced': 'Розширений',
            'Survey': 'Огляд',
        },
        'off': 'Вимкнено',
        'on': 'Увімкнено',
        'useDefault': 'Використовувати за замовчуванням',
        'useCustom': 'Використовувати користувацький',
        'saveChanges': 'Зберегти зміни',
        'saved': 'Збережено',
        'Connection': {
            'connectionInformation': 'Інформація про з\'єднання',
            'connection': 'З\'єднання',
            'isp': 'ISP',
            'colocationCenter': 'Центр колокації',
            'yourDevice': 'Ваш пристрій',
            'connectionType': 'Тип з\'єднання',
            'publicIP': 'Публічний IP',
            'deviceInformation': 'Інформація про пристрій',
        },
        'ConnectionPage': {
            'address': 'Адреса',
            'port': 'Порт',
            'adressDescription': 'Встановлює локальну адресу, на якій прослуховує проксі-сервер.',
            'portDescription': 'Встановлює локальний порт, на якому прослуховує проксі-сервер.',
        },
        'DNSPage': {
            'dns': 'DNS',
            'dnsDescription': 'Вказує адресу DNS-сервера, який буде використовуватися для розв\'язання доменних імен.',
            'useGoogle': 'Використовувати Google',
            'useCloudflare': 'Використовувати Cloudflare',
            'useQuad9': 'Використовувати Quad9',
            'useNextDNS': 'Використовувати NextDNS',
            'useYandex': 'Використовувати Yandex',
            'useAdGuard': 'Використовувати AdGuard',
            'useMullvad': 'Використовувати Mullvad',
            'useOpenDNS': 'Використовувати OpenDNS',
            'useCustom': 'Використовувати користувацький',
            'customAddress': 'Користувацька адреса',
            'customPort': 'Користувацький порт',
            'customAddressDescription': 'Встановлює користувацьку адресу та порт для DNS-сервера.',
        },
        'PatternPage': {
            'pattern': 'Шаблон',
            'patternDescription': 'Застосовує обхід DPI лише до пакетів, які відповідають заданим шаблонам доменів.',
        },
        'AdvancedPage': {
            'dnsipv4Only': 'Тільки DNS IPv4',
            'dnsipv4OnlyDescription': 'Використовувати лише сервери DNS IPv4.',
            'dnsOverHttps': 'DNS через HTTPS',
            'dnsOverHttpsDescription': 'Використовувати DNS через HTTPS.',
            'systemProxy': 'Системний проксі',
            'systemProxyDescription': 'Використовувати налаштування проксі-сервера системи.',
            'useProxy': 'Використовувати проксі',
            'useProxyDescription': 'Використовувати проксі-сервер.',
            'timeout': 'Тайм-аут',
            'timeoutDescription': 'Встановити тайм-аут для DNS-запитів. (Сек)',
            'clientHelloChunkSize': 'Розмір частини клієнта Hello',
            'clientHelloChunkSizeDescription': 'Встановити розмір частини клієнта hello.',
        },
        'SurveyPage': {
            'survey': 'Огляд',
            'surveySubtitle': 'Ми хотіли б почути вашу думку!',
        }
    },
    'ir': {
        'pressToShow': 'نمایش',
        'Titles': {
            'General': 'عمومی',
            'Connection': 'اتصال',
            'DNS': 'DNS',
            'Pattern': 'الگو',
            'Advanced': 'پیشرفته',
            'Survey': 'نظرسنجی',
        },
        'off': 'خاموش',
        'on': 'روشن',
        'useDefault': 'استفاده از پیش‌فرض',
        'useCustom': 'استفاده از سفارشی',
        'saveChanges': 'ذخیره تغییرات',
        'saved': 'ذخیره شده',
        'Connection': {
            'connectionInformation': 'اطلاعات اتصال',
            'connection': 'اتصال',
            'isp': 'ISP',
            'colocationCenter': 'مرکز هم‌مکانی',
            'yourDevice': 'دستگاه شما',
            'connectionType': 'نوع اتصال',
            'publicIP': 'IP عمومی',
            'deviceInformation': 'اطلاعات دستگاه',
        },
        'ConnectionPage': {
            'address': 'آدرس',
            'port': 'پورت',
            'adressDescription': 'آدرس محلی که سرور پروکسی به آن گوش می‌دهد را تنظیم کنید.',
            'portDescription': 'پورت محلی که سرور پروکسی به آن گوش می‌دهد را تنظیم کنید.',
        },
        'DNSPage': {
            'dns': 'DNS',
            'dnsDescription': 'آدرس سرور DNS که برای حل نام‌های دامنه استفاده می‌شود را مشخص کنید.',
            'useGoogle': 'استفاده از گوگل',
            'useCloudflare': 'استفاده از Cloudflare',
            'useQuad9': 'استفاده از Quad9',
            'useNextDNS': 'استفاده از NextDNS',
            'useYandex': 'استفاده از Yandex',
            'useAdGuard': 'استفاده از AdGuard',
            'useMullvad': 'استفاده از Mullvad',
            'useOpenDNS': 'استفاده از OpenDNS',
            'useCustom': 'استفاده از سفارشی',
            'customAddress': 'آدرس سفارشی',
            'customPort': 'پورت سفارشی',
            'customAddressDescription': 'آدرس و پورت سفارشی برای سرور DNS را تنظیم کنید.',
        },
        'PatternPage': {
            'pattern': 'الگو',
            'patternDescription': 'فقط به بسته‌هایی که با الگوهای دامنه داده شده مطابقت دارند، دور زدن DPI را اعمال کنید.',
        },
        'AdvancedPage': {
            'dnsipv4Only': 'فقط DNS IPv4',
            'dnsipv4OnlyDescription': 'فقط از سرورهای DNS IPv4 استفاده کنید.',
            'dnsOverHttps': 'DNS روی HTTPS',
            'dnsOverHttpsDescription': 'از DNS روی HTTPS استفاده کنید.',
            'systemProxy': 'پروکسی سیستم',
            'systemProxyDescription': 'از تنظیمات پروکسی سیستم استفاده کنید.',
            'useProxy': 'استفاده از پروکسی',
            'useProxyDescription': 'از سرور پروکسی استفاده کنید.',
            'timeout': 'زمان‌سنجی',
            'timeoutDescription': 'زمان‌سنجی برای درخواست‌های DNS را تنظیم کنید. (ثانیه)',
            'clientHelloChunkSize': 'اندازه تکه Client Hello',
            'clientHelloChunkSizeDescription': 'اندازه تکه client hello را تنظیم کنید.',
        },
        'SurveyPage': {
            'survey': 'نظرسنجی',
            'surveySubtitle': 'ما دوست داریم نظر شما را بشنویم!',
        }
    },
    'gr': {
        'pressToShow': 'Εμφάνιση',
        'Titles': {
            'General': 'Γενικά',
            'Connection': 'Σύνδεση',
            'DNS': 'DNS',
            'Pattern': 'Μοτίβο',
            'Advanced': 'Προχωρημένος',
            'Survey': 'Έρευνα',
        },
        'off': 'Απενεργοποιημένο',
        'on': 'Ενεργοποιημένο',
        'useDefault': 'Χρησιμοποιήστε προεπιλογή',
        'useCustom': 'Χρησιμοποιήστε προσαρμοσμένο',
        'saveChanges': 'Αποθήκευση αλλαγών',
        'saved': 'Αποθηκευμένο',
        'Connection': {
            'connectionInformation': 'Πληροφορίες σύνδεσης',
            'connection': 'Σύνδεση',
            'isp': 'ISP',
            'colocationCenter': 'Κέντρο Συγκέντρωσης',
            'yourDevice': 'Η συσκευή σας',
            'connectionType': 'Τύπος σύνδεσης',
            'publicIP': 'Δημόσιο IP',
            'deviceInformation': 'Πληροφορίες συσκευής',
        },
        'ConnectionPage': {
            'address': 'Διεύθυνση',
            'port': 'Θύρα',
            'adressDescription': 'Ορίζει τη διεύθυνση τοπικού υπολογιστή στην οποία ακούει ο διακομιστής μεσολάβησης.',
            'portDescription': 'Ορίζει τη θύρα τοπικού υπολογιστή στην οποία ακούει ο διακομιστής μεσολάβησης.',
        },
        'DNSPage': {
            'dns': 'DNS',
            'dnsDescription': 'Καθορίζει τη διεύθυνση του διακομιστή DNS που θα χρησιμοποιηθεί για την επίλυση ονομάτων τομέα.',
            'useGoogle': 'Χρησιμοποιήστε το Google',
            'useCloudflare': 'Χρησιμοποιήστε το Cloudflare',
            'useQuad9': 'Χρησιμοποιήστε το Quad9',
            'useNextDNS': 'Χρησιμοποιήστε το NextDNS',
            'useYandex': 'Χρησιμοποιήστε το Yandex',
            'useAdGuard': 'Χρησιμοποιήστε το AdGuard',
            'useMullvad': 'Χρησιμοποιήστε το Mullvad',
            'useOpenDNS': 'Χρησιμοποιήστε το OpenDNS',
            'useCustom': 'Χρησιμοποιήστε προσαρμοσμένο',
            'customAddress': 'Προσαρμοσμένη διεύθυνση',
            'customPort': 'Προσαρμοσμένη θύρα',
            'customAddressDescription': 'Ορίζει τη διεύθυνση και τη θύρα του διακομιστή DNS.',
        },
        'PatternPage': {
            'pattern': 'Μοτίβο',
            'patternDescription': 'Εφαρμόζει την παράκαμψη DPI μόνο σε πακέτα που ταιριάζουν με τα καθορισμένα μοτίβα τομέα.',
        },
        'AdvancedPage': {
            'dnsipv4Only': 'Μόνο DNS IPv4',
            'dnsipv4OnlyDescription': 'Χρησιμοποιήστε μόνο διακομιστές DNS IPv4.',
            'dnsOverHttps': 'DNS μέσω HTTPS',
            'dnsOverHttpsDescription': 'Χρησιμοποιήστε DNS μέσω HTTPS.',
            'systemProxy': 'Σύστημα μεσολάβησης',
            'systemProxyDescription': 'Χρησιμοποιήστε τις ρυθμίσεις μεσολάβησης του συστήματος.',
            'useProxy': 'Χρησιμοποιήστε μεσολάβηση',
            'useProxyDescription': 'Χρησιμοποιήστε τον διακομιστή μεσολάβησης.',
            'timeout': 'Χρονικό όριο',
            'timeoutDescription': 'Ορίζει το χρονικό όριο για τα ερωτήματα DNS. (Δευτ)',
            'clientHelloChunkSize': 'Μέγεθος τμήματος Client Hello',
            'clientHelloChunkSizeDescription': 'Ορίζει το μέγεθος του τμήματος client hello.',
        },
        'SurveyPage': {
            'survey': 'Έρευνα',
            'surveySubtitle': 'Θα θέλαμε να ακούσουμε τα σχόλιά σας!',
        }
    },
    'az': {
        'pressToShow': 'Göstər',
        'Titles': {
            'General': 'Ümumi',
            'Connection': 'Bağlantı',
            'DNS': 'DNS',
            'Pattern': 'Nümunə',
            'Advanced': 'İrəliləmiş',
            'Survey': 'Sorğu',
        },
        'off': 'Söndürülmüş',
        'on': 'Yandırılmış',
        'useDefault': 'Varsayılanı istifadə et',
        'useCustom': 'Xüsusi istifadə et',
        'saveChanges': 'Dəyişiklikləri saxla',
        'saved': 'Saxlanılıb',
        'Connection': {
            'connectionInformation': 'Bağlantı məlumatları',
            'connection': 'Bağlantı',
            'isp': 'ISP',
            'colocationCenter': 'Mərkəz',
            'yourDevice': 'Cihazınız',
            'connectionType': 'Bağlantı növü',
            'publicIP': 'İctimai IP',
            'deviceInformation': 'Cihaz məlumatları',
        },
        'ConnectionPage': {
            'address': 'Ünvan',
            'port': 'Port',
            'adressDescription': 'Proxy serverinin dinlədiyi yerli ünvanı təyin edir.',
            'portDescription': 'Proxy serverinin dinlədiyi yerli portu təyin edir.',
        },
        'DNSPage': {
            'dns': 'DNS',
            'dnsDescription': 'Domen adlarını həll etmək üçün istifadə olunacaq DNS serverinin ünvanını təyin edir.',
            'useGoogle': 'Google istifadə et',
            'useCloudflare': 'Cloudflare istifadə et',
            'useQuad9': 'Quad9 istifadə et',
            'useNextDNS': 'NextDNS istifadə et',
            'useYandex': 'Yandex istifadə et',
            'useAdGuard': 'AdGuard istifadə et',
            'useMullvad': 'Mullvad istifadə et',
            'useOpenDNS': 'OpenDNS istifadə et',
            'useCustom': 'Xüsusi istifadə et',
            'customAddress': 'Xüsusi ünvan',
            'customPort': 'Xüsusi port',
            'customAddressDescription': 'DNS serveri üçün xüsusi ünvan və portu təyin edir.',
        },
        'PatternPage': {
            'pattern': 'Nümunə',
            'patternDescription': 'Verilmiş domen nümunələri ilə uyğun gələn paketlərə yalnız DPI keçidini tətbiq edir.',
        },
        'AdvancedPage': {
            'dnsipv4Only': 'Yalnız DNS IPv4',
            'dnsipv4OnlyDescription': 'Yalnız IPv4 DNS serverlərini istifadə edin.',
            'dnsOverHttps': 'HTTPS üzərindən DNS',
            'dnsOverHttpsDescription': 'HTTPS üzərindən DNS istifadə edin.',
            'systemProxy': 'Sistem proxy',
            'systemProxyDescription': 'Sistem proxy ayarlarını istifadə edin.',
            'useProxy': 'Proxy istifadə et',
            'useProxyDescription': 'Proxy serverini istifadə edin.',
            'timeout': 'Vaxt aşımı',
            'timeoutDescription': 'DNS sorğuları üçün vaxt aşımını təyin edir. (Saniyə)',
            'clientHelloChunkSize': 'Müştəri Hello parçasının ölçüsü',
            'clientHelloChunkSizeDescription': 'Müştəri hello parçasının ölçüsünü təyin edir.',
        },
        'SurveyPage': {
            'survey': 'Sorğu',
            'surveySubtitle': 'Fikrinizi eşitmək istərdik!',
        }
    }


};

export type LanguageList = keyof typeof language;
export type LanguageType = typeof language['en'];
export default language;