
export default {

    'en': {

        'yes': 'Yes',
        'no': 'No',
        'ok': 'OK',
        'cancel': 'Cancel',
        'close': 'Close',

        'dialog': {
            'needSpoofTitle': 'SpoofDPI Not Installed',
            'needSpoofDescription': 'SpoofDPI is not installed, SpoofDPI is not available on your device for the MacDPI application to work.\n\nInstall SpoofDPI?',
            'spoofInstallTitle': 'SpoofDPI Installed Successfully',
            'spoofInstallDescription': 'You are now ready to use MacDPI!',
        },

        'app': {
            'updateAvailable': 'Update Available',
            'name': 'App Name',
            'description': 'App Description',
            'version': 'Version',
            'settings': 'Settings',
            'preferences': 'Preferences',
            'resetPreferences': 'Reset Preferences',
            'preferencesList': {
                'showTitle': 'Show Title',
                'notifications': 'Notifications',
                'launchAtLogin': 'Launch at Login',
            },
            'about': 'About',
            'aboutList': {
                'version': 'Version',
                'author': 'Author',
                'license': 'License',
            }
        },

        'language': 'Language',
        'languages': [
            { name: '🇬🇧 English', code: 'en' },
            { name: '🇹🇷 Turkish', code: 'tr' },
            { name: '🇩🇪 German', code: 'de' },
            { name: '🇪🇸 Spanish', code: 'es' },
            { name: '🇫🇷 French', code: 'fr' },
            { name: '🇮🇹 Italian', code: 'it' },
            { name: '🇧🇷 Portuguese', code: 'pt' },
            { name: '🇷🇺 Russian', code: 'ru' },
            { name: '🇯🇵 Japanese', code: 'ja' },
            { name: '🇰🇷 Korean', code: 'ko' },
            { name: '🇨🇳 Chinese', code: 'zh' },
            { name: '🇸🇦 Arabic', code: 'ar' },
            { name: '🇵🇱 Polish', code: 'pl' },
            { name: '🇺🇦 Ukrainian', code: 'uk' },
            { name: '🇮🇷 Persian', code: 'ir' },
            { name: '🇬🇷 Greek', code: 'gr' },
            { name: '🇦🇿 Azerbaijani', code: 'az' }
        ],

        'exit': 'Exit',

        'turn': {
            'on': 'Turn On',
            'off': 'Turn Off'
        },

    },


    'tr': {

        'yes': 'Evet',
        'no': 'Hayır',
        'ok': 'Tamam',
        'cancel': 'İptal',
        'close': 'Kapat',
        'dialog': {
            'needSpoofTitle': 'SpoofDPI Yüklü Değil',
            'needSpoofDescription': 'SpoofDPI yüklü değil, MacDPI uygulamasının çalışması için cihazınızda SpoofDPI bulunmuyor.\n\nSpoofDPI yüklemek ister misiniz?',
            'spoofInstallTitle': 'SpoofDPI Başarıyla Yüklendi',
            'spoofInstallDescription': 'Artık MacDPI\'yi kullanmaya hazırsınız!',
        },

        'app': {
            'updateAvailable': 'Güncelleme Mevcut',
            'name': 'Uygulama Adı',
            'description': 'Uygulama Açıklaması',
            'version': 'Sürüm',
            'settings': 'Ayarlar',
            'preferences': 'Tercihler',
            'resetPreferences': 'Tercihleri Sıfırla',
            'preferencesList': {
                'showTitle': 'Başlığı Göster',
                'notifications': 'Bildirimler',
                'launchAtLogin': 'Girişte Başlat',
            },
            'about': 'Hakkında',
            'aboutList': {
                'version': 'Sürüm',
                'author': 'Yazar',
                'license': 'Lisans',
            }
        },

        'language': 'Dil',
        'languages': [
            { name: '🇬🇧 İngilizce', code: 'en' },
            { name: '🇹🇷 Türkçe', code: 'tr' },
            { name: '🇩🇪 Almanca', code: 'de' },
            { name: '🇪🇸 İspanyolca', code: 'es' },
            { name: '🇫🇷 Fransızca', code: 'fr' },
            { name: '🇮🇹 İtalyanca', code: 'it' },
            { name: '🇧🇷 Portekizce', code: 'pt' },
            { name: '🇷🇺 Rusça', code: 'ru' },
            { name: '🇯🇵 Japonca', code: 'ja' },
            { name: '🇰🇷 Korece', code: 'ko' },
            { name: '🇨🇳 Çince', code: 'zh' },
            { name: '🇸🇦 Arapça', code: 'ar' },
            { name: '🇵🇱 Lehçe', code: 'pl' },
            { name: '🇺🇦 Ukraynaca', code: 'uk' },
            { name: '🇮🇷 Farsça', code: 'ir' },
            { name: '🇬🇷 Yunanca', code: 'gr' },
            { name: '🇦🇿 Azerice', code: 'az' }
        ],

        'exit': 'Çıkış',

        'turn': {
            'on': 'Aç',
            'off': 'Kapat'
        },

    },


    'de': {

        'yes': 'Ja',
        'no': 'Nein',
        'ok': 'OK',
        'cancel': 'Abbrechen',
        'close': 'Schließen',
        'dialog': {
            'needSpoofTitle': 'SpoofDPI nicht installiert',
            'needSpoofDescription': 'SpoofDPI ist nicht installiert, SpoofDPI ist auf Ihrem Gerät nicht verfügbar, damit die MacDPI-Anwendung funktioniert.\n\nSpoofDPI installieren?',
            'spoofInstallTitle': 'SpoofDPI erfolgreich installiert',
            'spoofInstallDescription': 'Sie sind jetzt bereit, MacDPI zu verwenden!',
        },

        'app': {
            'updateAvailable': 'Update verfügbar',
            'name': 'App Name',
            'description': 'App Beschreibung',
            'version': 'Version',
            'settings': 'Einstellungen',
            'preferences': 'Präferenzen',
            'resetPreferences': 'Präferenzen zurücksetzen',
            'preferencesList': {
                'showTitle': 'Titel anzeigen',
                'notifications': 'Benachrichtigungen',
                'launchAtLogin': 'Beim Anmelden starten',
            },
            'about': 'Über',
            'aboutList': {
                'version': 'Version',
                'author': 'Autor',
                'license': 'Lizenz',
            }
        },

        'language': 'Sprache',
        'languages': [
            { name: '🇬🇧 Englisch', code: 'en' },
            { name: '🇹🇷 Türkisch', code: 'tr' },
            { name: '🇩🇪 Deutsch', code: 'de' },
            { name: '🇪🇸 Spanisch', code: 'es' },
            { name: '🇫🇷 Französisch', code: 'fr' },
            { name: '🇮🇹 Italienisch', code: 'it' },
            { name: '🇧🇷 Portugiesisch', code: 'pt' },
            { name: '🇷🇺 Russisch', code: 'ru' },
            { name: '🇯🇵 Japanisch', code: 'ja' },
            { name: '🇰🇷 Koreanisch', code: 'ko' },
            { name: '🇨🇳 Chinesisch', code: 'zh' },
            { name: '🇸🇦 Arabisch', code: 'ar' },
            { name: '🇵🇱 Polnisch', code: 'pl' },
            { name: '🇺🇦 Ukrainisch', code: 'uk' },
            { name: '🇮🇷 Persisch', code: 'ir' },
            { name: '🇬🇷 Griechisch', code: 'gr' },
            { name: '🇦🇿 Aserbaidschanisch', code: 'az' }
        ],

        'exit': 'Ausfahrt',

        'turn': {
            'on': 'Ein',
            'off': 'Aus'
        },

    },

    'es': {
        'yes': 'Sí',
        'no': 'No',
        'ok': 'OK',
        'cancel': 'Cancelar',
        'close': 'Cerrar',
        'dialog': {
            'needSpoofTitle': 'SpoofDPI no instalado',
            'needSpoofDescription': 'SpoofDPI no está instalado, SpoofDPI no está disponible en su dispositivo para que la aplicación MacDPI funcione.\n\n¿Instalar SpoofDPI?',
            'spoofInstallTitle': 'SpoofDPI instalado con éxito',
            'spoofInstallDescription': '¡Ahora estás listo para usar MacDPI!',
        },
        'app': {
            'updateAvailable': 'Actualización disponible',
            'name': 'Nombre de la aplicación',
            'description': 'Descripción de la aplicación',
            'version': 'Versión',
            'settings': 'Configuraciones',
            'preferences': 'Preferencias',
            'resetPreferences': 'Restablecer preferencias',
            'preferencesList': {
                'showTitle': 'Mostrar título',
                'notifications': 'Notificaciones',
                'launchAtLogin': 'Iniciar al iniciar sesión',
            },
            'about': 'Acerca de',
            'aboutList': {
                'version': 'Versión',
                'author': 'Autor',
                'license': 'Licencia',
            },
        },
        'language': 'Idioma',
        'languages': [
            { name: '🇬🇧 Inglés', code: 'en' },
            { name: '🇹🇷 Turco', code: 'tr' },
            { name: '🇩🇪 Alemán', code: 'de' },
            { name: '🇪🇸 Español', code: 'es' },
            { name: '🇫🇷 Francés', code: 'fr' },
            { name: '🇮🇹 Italiano', code: 'it' },
            { name: '🇧🇷 Portugués', code: 'pt' },
            { name: '🇷🇺 Ruso', code: 'ru' },
            { name: '🇯🇵 Japonés', code: 'ja' },
            { name: '🇰🇷 Coreano', code: 'ko' },
            { name: '🇨🇳 Chino', code: 'zh' },
            { name: '🇸🇦 Árabe', code: 'ar' },
            { name: '🇵🇱 Polaco', code: 'pl' },
            { name: '🇺🇦 Ucraniano', code: 'uk' },
            { name: '🇮🇷 Persa', code: 'ir' },
            { name: '🇬🇷 Griego', code: 'gr' },
            { name: '🇦🇿 Azerí', code: 'az' }
        ],
        'exit': 'Salir',
        'turn': {
            'on': 'Encender',
            'off': 'Apagar'
        },
    },

    'fr': {
        'yes': 'Oui',
        'no': 'Non',
        'ok': 'OK',
        'cancel': 'Annuler',
        'close': 'Fermer',
        'dialog': {
            'needSpoofTitle': 'SpoofDPI non installé',
            'needSpoofDescription': 'SpoofDPI n\'est pas installé, SpoofDPI n\'est pas disponible sur votre appareil pour que l\'application MacDPI fonctionne.\n\nInstaller SpoofDPI ?',
            'spoofInstallTitle': 'SpoofDPI installé avec succès',
            'spoofInstallDescription': 'Vous êtes maintenant prêt à utiliser MacDPI !',
        },
        'app': {
            'updateAvailable': 'Mise à jour disponible',
            'name': 'Nom de l\'application',
            'description': 'Description de l\'application',
            'version': 'Version',
            'settings': 'Paramètres',
            'preferences': 'Préférences',
            'resetPreferences': 'Réinitialiser les préférences',
            'preferencesList': {
                'showTitle': 'Afficher le titre',
                'notifications': 'Notifications',
                'launchAtLogin': 'Lancer à la connexion',
            },
            'about': 'À propos',
            'aboutList': {
                'version': 'Version',
                'author': 'Auteur',
                'license': 'Licence',
            },
        },
        'language': 'Langue',
        'languages': [
            { name: '🇬🇧 Anglais', code: 'en' },
            { name: '🇹🇷 Turc', code: 'tr' },
            { name: '🇩🇪 Allemand', code: 'de' },
            { name: '🇪🇸 Espagnol', code: 'es' },
            { name: '🇫🇷 Français', code: 'fr' },
            { name: '🇮🇹 Italien', code: 'it' },
            { name: '🇧🇷 Portugais', code: 'pt' },
            { name: '🇷🇺 Russe', code: 'ru' },
            { name: '🇯🇵 Japonais', code: 'ja' },
            { name: '🇰🇷 Coréen', code: 'ko' },
            { name: '🇨🇳 Chinois', code: 'zh' },
            { name: '🇸🇦 Arabe', code: 'ar' },
            { name: '🇵🇱 Polonais', code: 'pl' },
            { name: '🇺🇦 Ukrainien', code: 'uk' },
            { name: '🇮🇷 Persan', code: 'ir' },
            { name: '🇬🇷 Grec', code: 'gr' },
            { name: '🇦🇿 Azéri', code: 'az' }
        ],
        'exit': 'Sortir',
        'turn': {
            'on': 'Allumer',
            'off': 'Éteindre'
        },
    },

    'it': {
        'yes': 'Sì',
        'no': 'No',
        'ok': 'OK',
        'cancel': 'Annulla',
        'close': 'Chiudi',
        'dialog': {
            'needSpoofTitle': 'SpoofDPI non installato',
            'needSpoofDescription': 'SpoofDPI non è installato, SpoofDPI non è disponibile sul tuo dispositivo affinché l\'applicazione MacDPI funzioni.\n\nInstallare SpoofDPI?',
            'spoofInstallTitle': 'SpoofDPI installato con successo',
            'spoofInstallDescription': 'Ora sei pronto per usare MacDPI!',
        },
        'app': {
            'updateAvailable': 'Aggiornamento disponibile',
            'name': 'Nome dell\'app',
            'description': 'Descrizione dell\'app',
            'version': 'Versione',
            'settings': 'Impostazioni',
            'preferences': 'Preferenze',
            'resetPreferences': 'Ripristina preferenze',
            'preferencesList': {
                'showTitle': 'Mostra titolo',
                'notifications': 'Notifiche',
                'launchAtLogin': 'Avvia all\'accesso',
            },
            'about': 'Informazioni',
            'aboutList': {
                'version': 'Versione',
                'author': 'Autore',
                'license': 'Licenza',
            },
        },
        'language': 'Lingua',
        'languages': [
            { name: '🇬🇧 Inglese', code: 'en' },
            { name: '🇹🇷 Turco', code: 'tr' },
            { name: '🇩🇪 Tedesco', code: 'de' },
            { name: '🇪🇸 Spagnolo', code: 'es' },
            { name: '🇫🇷 Francese', code: 'fr' },
            { name: '🇮🇹 Italiano', code: 'it' },
            { name: '🇧🇷 Portoghese', code: 'pt' },
            { name: '🇷🇺 Russo', code: 'ru' },
            { name: '🇯🇵 Giapponese', code: 'ja' },
            { name: '🇰🇷 Coreano', code: 'ko' },
            { name: '🇨🇳 Cinese', code: 'zh' },
            { name: '🇸🇦 Arabo', code: 'ar' },
            { name: '🇵🇱 Polacco', code: 'pl' },
            { name: '🇺🇦 Ucraino', code: 'uk' },
            { name: '🇮🇷 Persiano', code: 'ir' },
            { name: '🇬🇷 Greco', code: 'gr' },
            { name: '🇦🇿 Azero', code: 'az' }
        ],
        'exit': 'Esci',
        'turn': {
            'on': 'Accendi',
            'off': 'Spegni'
        },
    },
    'pt': {
        'yes': 'Sim',
        'no': 'Não',
        'ok': 'OK',
        'cancel': 'Cancelar',
        'close': 'Fechar',
        'dialog': {
            'needSpoofTitle': 'SpoofDPI não instalado',
            'needSpoofDescription': 'SpoofDPI não está instalado, SpoofDPI não está disponível no seu dispositivo para que o aplicativo MacDPI funcione.\n\nInstalar SpoofDPI?',
            'spoofInstallTitle': 'SpoofDPI instalado com sucesso',
            'spoofInstallDescription': 'Agora você está pronto para usar o MacDPI!',
        },
        'app': {
            'updateAvailable': 'Atualização disponível',
            'name': 'Nome do aplicativo',
            'description': 'Descrição do aplicativo',
            'version': 'Versão',
            'settings': 'Configurações',
            'preferences': 'Preferências',
            'resetPreferences': 'Redefinir preferências',
            'preferencesList': {
                'showTitle': 'Mostrar título',
                'notifications': 'Notificações',
                'launchAtLogin': 'Iniciar ao fazer login',
            },
            'about': 'Sobre',
            'aboutList': {
                'version': 'Versão',
                'author': 'Autor',
                'license': 'Licença',
            },
        },
        'language': 'Idioma',
        'languages': [
            { name: '🇬🇧 Inglês', code: 'en' },
            { name: '🇹🇷 Turco', code: 'tr' },
            { name: '🇩🇪 Alemão', code: 'de' },
            { name: '🇪🇸 Espanhol', code: 'es' },
            { name: '🇫🇷 Francês', code: 'fr' },
            { name: '🇮🇹 Italiano', code: 'it' },
            { name: '🇧🇷 Português', code: 'pt' },
            { name: '🇷🇺 Russo', code: 'ru' },
            { name: '🇯🇵 Japonês', code: 'ja' },
            { name: '🇰🇷 Coreano', code: 'ko' },
            { name: '🇨🇳 Chinês', code: 'zh' },
            { name: '🇸🇦 Árabe', code: 'ar' },
            { name: '🇵🇱 Polonês', code: 'pl' },
            { name: '🇺🇦 Ucraniano', code: 'uk' },
            { name: '🇮🇷 Persa', code: 'ir' },
            { name: '🇬🇷 Grego', code: 'gr' },
            { name: '🇦🇿 Azerbaijano', code: 'az' }
        ],
        'exit': 'Sair',
        'turn': {
            'on': 'Ligar',
            'off': 'Desligar'
        },
    },
    'ru': {
        'yes': 'Да',
        'no': 'Нет',
        'ok': 'ОК',
        'cancel': 'Отмена',
        'close': 'Закрыть',
        'dialog': {
            'needSpoofTitle': 'SpoofDPI не установлен',
            'needSpoofDescription': 'SpoofDPI не установлен, SpoofDPI недоступен на вашем устройстве для работы приложения MacDPI.\n\nУстановить SpoofDPI?',
            'spoofInstallTitle': 'SpoofDPI успешно установлен',
            'spoofInstallDescription': 'Теперь вы готовы использовать MacDPI!',
        },
        'app': {
            'updateAvailable': 'Доступно обновление',
            'name': 'Имя приложения',
            'description': 'Описание приложения',
            'version': 'Версия',
            'settings': 'Настройки',
            'preferences': 'Предпочтения',
            'resetPreferences': 'Сбросить предпочтения',
            'preferencesList': {
                'showTitle': 'Показать название',
                'notifications': 'Уведомления',
                'launchAtLogin': 'Запускать при входе',
            },
            'about': 'О программе',
            'aboutList': {
                'version': 'Версия',
                'author': 'Автор',
                'license': 'Лицензия',
            },
        },
        'language': 'Язык',
        'languages': [
            { name: '🇬🇧 Английский', code: 'en' },
            { name: '🇹🇷 Турецкий', code: 'tr' },
            { name: '🇩🇪 Немецкий', code: 'de' },
            { name: '🇪🇸 Испанский', code: 'es' },
            { name: '🇫🇷 Французский', code: 'fr' },
            { name: '🇮🇹 Итальянский', code: 'it' },
            { name: '🇧🇷 Португальский', code: 'pt' },
            { name: '🇷🇺 Русский', code: 'ru' },
            { name: '🇯🇵 Японский', code: 'ja' },
            { name: '🇰🇷 Корейский', code: 'ko' },
            { name: '🇨🇳 Китайский', code: 'zh' },
            { name: '🇸🇦 Арабский', code: 'ar' },
            { name: '🇵🇱 Польский', code: 'pl' },
            { name: '🇺🇦 Украинский', code: 'uk' },
            { name: '🇮🇷 Персидский', code: 'ir' },
            { name: '🇬🇷 Греческий', code: 'gr' },
            { name: '🇦🇿 Азербайджанский', code: 'az' }
        ],
        'exit': 'Выход',
        'turn': {
            'on': 'Включить',
            'off': 'Выключить'
        },
    },
    'ja': {
        'yes': 'はい',
        'no': 'いいえ',
        'ok': 'OK',
        'cancel': 'キャンセル',
        'close': '閉じる',
        'dialog': {
            'needSpoofTitle': 'SpoofDPIがインストールされていません',
            'needSpoofDescription': 'SpoofDPIがインストールされていません。MacDPIアプリケーションが機能するために、デバイスにSpoofDPIが必要です。\n\nSpoofDPIをインストールしますか？',
            'spoofInstallTitle': 'SpoofDPIが正常にインストールされました',
            'spoofInstallDescription': 'これでMacDPIを使用する準備が整いました！',
        },
        'app': {
            'updateAvailable': 'アップデートが利用可能',
            'name': 'アプリ名',
            'description': 'アプリの説明',
            'version': 'バージョン',
            'settings': '設定',
            'preferences': '設定',
            'resetPreferences': '設定をリセット',
            'preferencesList': {
                'showTitle': 'タイトルを表示',
                'notifications': '通知',
                'launchAtLogin': 'ログイン時に起動',
            },
            'about': 'アプリについて',
            'aboutList': {
                'version': 'バージョン',
                'author': '著者',
                'license': 'ライセンス',
            },
        },
        'language': '言語',
        'languages': [
            { name: '🇬🇧 英語', code: 'en' },
            { name: '🇹🇷 トルコ語', code: 'tr' },
            { name: '🇩🇪 ドイツ語', code: 'de' },
            { name: '🇪🇸 スペイン語', code: 'es' },
            { name: '🇫🇷 フランス語', code: 'fr' },
            { name: '🇮🇹 イタリア語', code: 'it' },
            { name: '🇧🇷 ポルトガル語', code: 'pt' },
            { name: '🇷🇺 ロシア語', code: 'ru' },
            { name: '🇯🇵 日本語', code: 'ja' },
            { name: '🇰🇷 韓国語', code: 'ko' },
            { name: '🇨🇳 中国語', code: 'zh' },
            { name: '🇸🇦 アラビア語', code: 'ar' },
            { name: '🇵🇱 ポーランド語', code: 'pl' },
            { name: '🇺🇦 ウクライナ語', code: 'uk' },
            { name: '🇮🇷 ペルシャ語', code: 'ir' },
            { name: '🇬🇷 ギリシャ語', code: 'gr' },
            { name: '🇦🇿 アゼルバイジャン語', code: 'az' }
        ],
        'exit': '終了',
        'turn': {
            'on': 'オン',
            'off': 'オフ'
        },
    },
    'ko': {
        'yes': '예',
        'no': '아니요',
        'ok': '확인',
        'cancel': '취소',
        'close': '닫기',
        'dialog': {
            'needSpoofTitle': 'SpoofDPI가 설치되지 않음',
            'needSpoofDescription': 'SpoofDPI가 설치되지 않았습니다. MacDPI 애플리케이션이 작동하려면 장치에 SpoofDPI가 필요합니다.\n\nSpoofDPI를 설치하시겠습니까?',
            'spoofInstallTitle': 'SpoofDPI가 성공적으로 설치됨',
            'spoofInstallDescription': '이제 MacDPI를 사용할 준비가 되었습니다!',
        },
        'app': {
            'updateAvailable': '업데이트 가능',
            'name': '앱 이름',
            'description': '앱 설명',
            'version': '버전',
            'settings': '설정',
            'preferences': '환경 설정',
            'resetPreferences': '환경 설정 재설정',
            'preferencesList': {
                'showTitle': '제목 표시',
                'notifications': '알림',
                'launchAtLogin': '로그인 시 시작',
            },
            'about': '정보',
            'aboutList': {
                'version': '버전',
                'author': '저자',
                'license': '라이센스',
            },
        },
        'language': '언어',
        'languages': [
            { name: '🇬🇧 영어', code: 'en' },
            { name: '🇹🇷 터키어', code: 'tr' },
            { name: '🇩🇪 독일어', code: 'de' },
            { name: '🇪🇸 스페인어', code: 'es' },
            { name: '🇫🇷 프랑스어', code: 'fr' },
            { name: '🇮🇹 이탈리아어', code: 'it' },
            { name: '🇧🇷 포르투갈어', code: 'pt' },
            { name: '🇷🇺 러시아어', code: 'ru' },
            { name: '🇯🇵 일본어', code: 'ja' },
            { name: '🇰🇷 한국어', code: 'ko' },
            { name: '🇨🇳 중국어', code: 'zh' },
            { name: '🇸🇦 아랍어', code: 'ar' },
            { name: '🇵🇱 폴란드어', code: 'pl' },
            { name: '🇺🇦 우크라이나어', code: 'uk' },
            { name: '🇮🇷 페르시아어', code: 'ir' },
            { name: '🇬🇷 그리스어', code: 'gr' },
            { name: '🇦🇿 아제르바이잔어', code: 'az' }
        ],
        'exit': '종료',
        'turn': {
            'on': '켜기',
            'off': '끄기'
        },
    },
    'zh': {
        'yes': '是',
        'no': '否',
        'ok': '确定',
        'cancel': '取消',
        'close': '关闭',
        'dialog': {
            'needSpoofTitle': 'SpoofDPI未安装',
            'needSpoofDescription': 'SpoofDPI未安装，SpoofDPI在您的设备上不可用，以便MacDPI应用程序正常工作。\n\n安装SpoofDPI？',
            'spoofInstallTitle': 'SpoofDPI安装成功',
            'spoofInstallDescription': '您现在可以使用MacDPI了！',
        },
        'app': {
            'updateAvailable': '可用更新',
            'name': '应用名称',
            'description': '应用描述',
            'version': '版本',
            'settings': '设置',
            'preferences': '首选项',
            'resetPreferences': '重置首选项',
            'preferencesList': {
                'showTitle': '显示标题',
                'notifications': '通知',
                'launchAtLogin': '登录时启动',
            },
            'about': '关于',
            'aboutList': {
                'version': '版本',
                'author': '作者',
                'license': '许可证',
            },
        },
        'language': '语言',
        'languages': [
            { name: '🇬🇧 英语', code: 'en' },
            { name: '🇹🇷 土耳其语', code: 'tr' },
            { name: '🇩🇪 德语', code: 'de' },
            { name: '🇪🇸 西班牙语', code: 'es' },
            { name: '🇫🇷 法语', code: 'fr' },
            { name: '🇮🇹 意大利语', code: 'it' },
            { name: '🇧🇷 葡萄牙语', code: 'pt' },
            { name: '🇷🇺 俄语', code: 'ru' },
            { name: '🇯🇵 日语', code: 'ja' },
            { name: '🇰🇷 韩语', code: 'ko' },
            { name: '🇨🇳 中文', code: 'zh' },
            { name: '🇸🇦 阿拉伯语', code: 'ar' },
            { name: '🇵🇱 波兰语', code: 'pl' },
            { name: '🇺🇦 乌克兰语', code: 'uk' },
            { name: '🇮🇷 波斯语', code: 'ir' },
            { name: '🇬🇷 希腊语', code: 'gr' },
            { name: '🇦🇿 阿塞拜疆语', code: 'az' }
        ],
        'exit': '退出',
        'turn': {
            'on': '开启',
            'off': '关闭'
        },
    },
    'ar': {
        'yes': 'نعم',
        'no': 'لا',
        'ok': 'حسنا',
        'cancel': 'إلغاء',
        'close': 'إغلاق',
        'dialog': {
            'needSpoofTitle': 'SpoofDPI غير مثبت',
            'needSpoofDescription': 'SpoofDPI غير مثبت، SpoofDPI غير متاح على جهازك حتى تعمل تطبيق MacDPI.\n\nهل تريد تثبيت SpoofDPI؟',
            'spoofInstallTitle': 'تم تثبيت SpoofDPI بنجاح',
            'spoofInstallDescription': 'أنت الآن جاهز لاستخدام MacDPI!',
        },
        'app': {
            'updateAvailable': 'تحديث متاح',
            'name': 'اسم التطبيق',
            'description': 'وصف التطبيق',
            'version': 'الإصدار',
            'settings': 'الإعدادات',
            'preferences': 'التفضيلات',
            'resetPreferences': 'إعادة تعيين التفضيلات',
            'preferencesList': {
                'showTitle': 'إظهار العنوان',
                'notifications': 'الإشعارات',
                'launchAtLogin': 'بدء التشغيل عند تسجيل الدخول',
            },
            'about': 'حول',
            'aboutList': {
                'version': 'الإصدار',
                'author': 'المؤلف',
                'license': 'الرخصة',
            },
        },
        'language': 'اللغة',
        'languages': [
            { name: '🇬🇧 الإنجليزية', code: 'en' },
            { name: '🇹🇷 التركية', code: 'tr' },
            { name: '🇩🇪 الألمانية', code: 'de' },
            { name: '🇪🇸 الإسبانية', code: 'es' },
            { name: '🇫🇷 الفرنسية', code: 'fr' },
            { name: '🇮🇹 الإيطالية', code: 'it' },
            { name: '🇧🇷 البرتغالية', code: 'pt' },
            { name: '🇷🇺 الروسية', code: 'ru' },
            { name: '🇯🇵 اليابانية', code: 'ja' },
            { name: '🇰🇷 الكورية', code: 'ko' },
            { name: '🇨🇳 الصينية', code: 'zh' },
            { name: '🇸🇦 العربية', code: 'ar' },
            { name: '🇵🇱 البولندية', code: 'pl' },
            { name: '🇺🇦 الأوكرانية', code: 'uk' },
            { name: '🇮🇷 الفارسية', code: 'ir' },
            { name: '🇬🇷 اليونانية', code: 'gr' },
            { name: '🇦🇿 الأذربيجانية', code: 'az' }
        ],
        'exit': 'خروج',
        'turn': {
            'on': 'تشغيل',
            'off': 'إيقاف'
        },
    },
    'pl': {
        'yes': 'Tak',
        'no': 'Nie',
        'ok': 'OK',
        'cancel': 'Anuluj',
        'close': 'Zamknij',
        'dialog': {
            'needSpoofTitle': 'SpoofDPI nie jest zainstalowany',
            'needSpoofDescription': 'SpoofDPI nie jest zainstalowany, SpoofDPI nie jest dostępny na Twoim urządzeniu, aby aplikacja MacDPI działała.\n\nZainstalować SpoofDPI?',
            'spoofInstallTitle': 'SpoofDPI zainstalowany pomyślnie',
            'spoofInstallDescription': 'Jesteś teraz gotowy do użycia MacDPI!',
        },
        'app': {
            'updateAvailable': 'Dostępna aktualizacja',
            'name': 'Nazwa aplikacji',
            'description': 'Opis aplikacji',
            'version': 'Wersja',
            'settings': 'Ustawienia',
            'preferences': 'Preferencje',
            'resetPreferences': 'Resetuj preferencje',
            'preferencesList': {
                'showTitle': 'Pokaż tytuł',
                'notifications': 'Powiadomienia',
                'launchAtLogin': 'Uruchom przy logowaniu',
            },
            'about': 'O aplikacji',
            'aboutList': {
                'version': 'Wersja',
                'author': 'Autor',
                'license': 'Licencja',
            },
        },
        'language': 'Język',
        'languages': [
            { name: '🇬🇧 Angielski', code: 'en' },
            { name: '🇹🇷 Turecki', code: 'tr' },
            { name: '🇩🇪 Niemiecki', code: 'de' },
            { name: '🇪🇸 Hiszpański', code: 'es' },
            { name: '🇫🇷 Francuski', code: 'fr' },
            { name: '🇮🇹 Włoski', code: 'it' },
            { name: '🇧🇷 Portugalski', code: 'pt' },
            { name: '🇷🇺 Rosyjski', code: 'ru' },
            { name: '🇯🇵 Japoński', code: 'ja' },
            { name: '🇰🇷 Koreański', code: 'ko' },
            { name: '🇨🇳 Chiński', code: 'zh' },
            { name: '🇸🇦 Arabski', code: 'ar' },
            { name: '🇵🇱 Polski', code: 'pl' },
            { name: '🇺🇦 Ukraiński', code: 'uk' },
            { name: '🇮🇷 Perski', code: 'ir' },
            { name: '🇬🇷 Grecki', code: 'gr' },
            { name: '🇦🇿 Azerbejdżański', code: 'az' }
        ],
        'exit': 'Wyjście',
        'turn': {
            'on': 'Włącz',
            'off': 'Wyłącz'
        },
    },
    'uk': {
        'yes': 'Так',
        'no': 'Ні',
        'ok': 'ОК',
        'cancel': 'Скасувати',
        'close': 'Закрити',
        'dialog': {
            'needSpoofTitle': 'SpoofDPI не встановлено',
            'needSpoofDescription': 'SpoofDPI не встановлено, SpoofDPI недоступний на вашому пристрої для роботи програми MacDPI.\n\nВстановити SpoofDPI?',
            'spoofInstallTitle': 'SpoofDPI успішно встановлено',
            'spoofInstallDescription': 'Тепер ви готові використовувати MacDPI!',
        },
        'app': {
            'updateAvailable': 'Доступне оновлення',
            'name': 'Назва програми',
            'description': 'Опис програми',
            'version': 'Версія',
            'settings': 'Налаштування',
            'preferences': 'Налаштування',
            'resetPreferences': 'Скинути налаштування',
            'preferencesList': {
                'showTitle': 'Показати назву',
                'notifications': 'Сповіщення',
                'launchAtLogin': 'Запускати при вході',
            },
            'about': 'Про програму',
            'aboutList': {
                'version': 'Версія',
                'author': 'Автор',
                'license': 'Ліцензія',
            },
        },
        'language': 'Мова',
        'languages': [
            { name: '🇬🇧 Англійська', code: 'en' },
            { name: '🇹🇷 Турецька', code: 'tr' },
            { name: '🇩🇪 Німецька', code: 'de' },
            { name: '🇪🇸 Іспанська', code: 'es' },
            { name: '🇫🇷 Французька', code: 'fr' },
            { name: '🇮🇹 Італійська', code: 'it' },
            { name: '🇧🇷 Португальська', code: 'pt' },
            { name: '🇷🇺 Російська', code: 'ru' },
            { name: '🇯🇵 Японська', code: 'ja' },
            { name: '🇰🇷 Корейська', code: 'ko' },
            { name: '🇨🇳 Китайська', code: 'zh' },
            { name: '🇸🇦 Арабська', code: 'ar' },
            { name: '🇵🇱 Польська', code: 'pl' },
            { name: '🇺🇦 Українська', code: 'uk' },
            { name: '🇮🇷 Перська', code: 'ir' },
            { name: '🇬🇷 Грецька', code: 'gr' },
            { name: '🇦🇿 Азербайджанська', code: 'az' }
        ],
        'exit': 'Вихід',
        'turn': {
            'on': 'Увімкнути',
            'off': 'Вимкнути'
        },
    },

    'ir': {
        'yes': 'بله',
        'no': 'خیر',
        'ok': 'تایید',
        'cancel': 'انصراف',
        'close': 'بستن',
        'dialog': {
            'needSpoofTitle': 'SpoofDPI نصب نشده است',
            'needSpoofDescription': 'SpoofDPI نصب نشده است، SpoofDPI در دستگاه شما در دسترس نیست تا برنامه MacDPI کار کند.\n\nآیا می‌خواهید SpoofDPI را نصب کنید؟',
            'spoofInstallTitle': 'SpoofDPI با موفقیت نصب شد',
            'spoofInstallDescription': 'شما اکنون آماده استفاده از MacDPI هستید!',
        },
        'app': {
            'updateAvailable': 'به روز رسانی در دسترس است',
            'name': 'نام برنامه',
            'description': 'توضیحات برنامه',
            'version': 'نسخه',
            'settings': 'تنظیمات',
            'preferences': 'ترجیحات',
            'resetPreferences': 'تنظیمات را بازنشانی کنید',
            'preferencesList': {
                'showTitle': 'عنوان را نشان بده',
                'notifications': 'اعلان‌ها',
                'launchAtLogin': 'در ورود به سیستم راه‌اندازی کنید',
            },
            'about': 'درباره',
            'aboutList': {
                'version': 'نسخه',
                'author': 'نویسنده',
                'license': 'مجوز',
            },
        },
        'language': 'زبان',
        'languages': [
            { name: '🇬🇧 انگلیسی', code: 'en' },
            { name: '🇹🇷 ترکی', code: 'tr' },
            { name: '🇩🇪 آلمانی', code: 'de' },
            { name: '🇪🇸 اسپانیایی', code: 'es' },
            { name: '🇫🇷 فرانسوی', code: 'fr' },
            { name: '🇮🇹 ایتالیایی', code: 'it' },
            { name: '🇧🇷 پرتغالی', code: 'pt' },
            { name: '🇷🇺 روسی', code: 'ru' },
            { name: '🇯🇵 ژاپنی', code: 'ja' },
            { name: '🇰🇷 کره‌ای', code: 'ko' },
            { name: '🇨🇳 چینی', code: 'zh' },
            { name: '🇸🇦 عربی', code: 'ar' },
            { name: '🇵🇱 لهستانی', code: 'pl' },
            { name: '🇺🇦 اوکراینی', code: 'uk' },
            { name: '🇮🇷 فارسی', code: 'ir' },
            { name: '🇬🇷 یونانی', code: 'gr' },
            { name: '🇦🇿 آذربایجانی', code: 'az' }
        ],
        'exit': 'خروج',
        'turn': {
            'on': 'روشن',
            'off': 'خاموش'
        },
    },

    'gr': {
        'yes': 'Ναι',
        'no': 'Όχι',
        'ok': 'Εντάξει',
        'cancel': 'Ακύρωση',
        'close': 'Κλείσιμο',
        'dialog': {
            'needSpoofTitle': 'SpoofDPI δεν είναι εγκατεστημένο',
            'needSpoofDescription': 'SpoofDPI δεν είναι εγκατεστημένο, SpoofDPI δεν είναι διαθέσιμο στη συσκευή σας για να λειτουργήσει η εφαρμογή MacDPI.\n\nΕγκατάσταση SpoofDPI;',
            'spoofInstallTitle': 'SpoofDPI εγκαταστάθηκε με επιτυχία',
            'spoofInstallDescription': 'Είστε τώρα έτοιμοι να χρησιμοποιήσετε το MacDPI!',
        },
        'app': {
            'updateAvailable': 'Διαθέσιμη ενημέρωση',
            'name': 'Όνομα εφαρμογής',
            'description': 'Περιγραφή εφαρμογής',
            'version': 'Έκδοση',
            'settings': 'Ρυθμίσεις',
            'preferences': 'Προτιμήσεις',
            'resetPreferences': 'Επαναφορά προτιμήσεων',
            'preferencesList': {
                'showTitle': 'Εμφάνιση τίτλου',
                'notifications': 'Ειδοποιήσεις',
                'launchAtLogin': 'Εκκίνηση κατά την είσοδο',
            },
            'about': 'Σχετικά',
            'aboutList': {
                'version': 'Έκδοση',
                'author': 'Συγγραφέας',
                'license': 'Άδεια',
            },
        },
        'language': 'Γλώσσα',
        'languages': [
            { name: '🇬🇧 Αγγλικά', code: 'en' },
            { name: '🇹🇷 Τουρκικά', code: 'tr' },
            { name: '🇩🇪 Γερμανικά', code: 'de' },
            { name: '🇪🇸 Ισπανικά', code: 'es' },
            { name: '🇫🇷 Γαλλικά', code: 'fr' },
            { name: '🇮🇹 Ιταλικά', code: 'it' },
            { name: '🇧🇷 Πορτογαλικά', code: 'pt' },
            { name: '🇷🇺 Ρωσικά', code: 'ru' },
            { name: '🇯🇵 Ιαπωνικά', code: 'ja' },
            { name: '🇰🇷 Κορεάτικα', code: 'ko' },
            { name: '🇨🇳 Κινέζικα', code: 'zh' },
            { name: '🇸🇦 Αραβικά', code: 'ar' },
            { name: '🇵🇱 Πολωνικά', code: 'pl' },
            { name: '🇺🇦 Ουκρανικά', code: 'uk' },
            { name: '🇮🇷 Φαρσί', code: 'ir' },
            { name: '🇬🇷 Ελληνικά', code: 'gr' },
            { name: '🇦🇿 Αζερμπαϊτζανικά', code: 'az' }
        ],
        'exit': 'Έξοδος',
        'turn': {
            'on': 'Ενεργοποίηση',
            'off': 'Απενεργοποίηση'
        },
    },
    'az': {
        'yes': 'Bəli',
        'no': 'Xeyr',
        'ok': 'Tamam',
        'cancel': 'İmtina et',
        'close': 'Bağla',
        'dialog': {
            'needSpoofTitle': 'SpoofDPI quraşdırılmayıb',
            'needSpoofDescription': 'SpoofDPI quraşdırılmayıb, SpoofDPI MacDPI tətbiqinin işləməsi üçün cihazınızda mövcud deyil.\n\nSpoofDPI quraşdırılsın?',
            'spoofInstallTitle': 'SpoofDPI uğurla quraşdırılıb',
            'spoofInstallDescription': 'İndi MacDPI-dən istifadə etməyə hazırsınız!',
        },
        'app': {
            'updateAvailable': 'Yeniləmə mövcuddur',
            'name': 'Tətbiq adı',
            'description': 'Tətbiq təsviri',
            'version': 'Versiya',
            'settings': 'Ayarlar',
            'preferences': 'Təqdimatlar',
            'resetPreferences': 'Təqdimatları sıfırla',
            'preferencesList': {
                'showTitle': 'Başlığı göstər',
                'notifications': 'Bildirişlər',
                'launchAtLogin': 'Girişdə işə sal',
            },
            'about': 'Haqqında',
            'aboutList': {
                'version': 'Versiya',
                'author': 'Müəllif',
                'license': 'Lisenziya',
            },
        },
        'language': 'Dil',
        'languages': [
            { name: '🇬🇧 İngilis', code: 'en' },
            { name: '🇹🇷 Türk', code: 'tr' },
            { name: '🇩🇪 Alman', code: 'de' },
            { name: '🇪🇸 İspan', code: 'es' },
            { name: '🇫🇷 Fransız', code: 'fr' },
            { name: '🇮🇹 İtalyan', code: 'it' },
            { name: '🇧🇷 Portuqal', code: 'pt' },
            { name: '🇷🇺 Rus', code: 'ru' },
            { name: '🇯🇵 Yapon', code: 'ja' },
            { name: '🇰🇷 Koreya', code: 'ko' },
            { name: '🇨🇳 Çin', code: 'zh' },
            { name: '🇸🇦 Ərəb', code: 'ar' },
            { name: '🇵🇱 Polyak', code: 'pl' },
            { name: '🇺🇦 Ukrayna', code: 'uk' },
            { name: '🇮🇷 Fars', code: 'ir' },
            { name: '🇬🇷 Yunan', code: 'gr' },
            { name: '🇦🇿 Azərbaycan', code: 'az' }
        ],
        'exit': 'Çıxış',
        'turn': {
            'on': 'Yandır',
            'off': 'Söndür'
        },
    },


}